# Generated by Django 5.2.1 on 2025-05-15 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('banner', models.ImageField(upload_to='category/')),
                ('icon', models.ImageField(upload_to='category/')),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=100)),
                ('banner_sub_title', models.CharField(max_length=100)),
                ('banner_image', models.ImageField(upload_to='banner/')),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('facebook', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('youtube', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('slogan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='blog/')),
                ('content', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chondrokanto.category')),
            ],
        ),
        migrations.CreateModel(
            name='album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='album/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chondrokanto.category')),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='video/')),
                ('video_link', models.CharField(max_length=300)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chondrokanto.album')),
            ],
        ),
    ]
